### PR TITLE
Add webpacker:install:tailwind generator 

### PR DESCRIPTION
**Pull request by jeremiahlukus**

### CODE REVIEW

**Comment by jeremiahlukus** [comment]
@tongueroo  I fixed the jest tests, and rubocop but the ruby tests are still broken since almost all fail.  These are issues from master I fixed. 

Also note i commented out 
https://github.com/tongueroo/jetpacker/pull/5/files#diff-862fd71230dc2fe817648e2da5199c0b9d659b20b28883984a06bde0052564e2L15

This did not break anything so maybe whatever was broken when you did this is now fixed 
https://github.com/jeremiahlukus/jetpacker/blob/tailwind/package/__tests__/config.js#L29
This test, tests that is added the test was failing saying it was double added to the list. 




Here is a demo app that used the flag with some added tailwind style 
https://github.com/jeremiahlukus/demoAuth-revise-Jets/compare/main...jetpacker#diff-9bbf2b8f54ef7cbd99b2afa1da3756582ef6d0a7d0da623fd093a1fe1b55736dR2

**Comment by jeremiahlukus** [comment]
Found a small issue

**Comment by jeremiahlukus** [comment]
Issue was related to postcss, @rails/webpacker uses an older version (we need postcss 8) so we are unable to use tailwindcss/nesting https://tailwindcss.com/docs/using-with-preprocessors (ie create custom css classes using tailwind classes then import in theme.scss). You can add these classes directly into theme.scss if needed. 

This only applies if you want to use tailwind classes to create new classes. 

Once you update from webpacker ill send a PR to fix tailwind since you do not use it.

**Comment by tongueroo** [comment]
Bummer. Thanks for the details and the effort. It sounds like it was a bit of a rabbithole. Thanks again.

**Comment by jeremiahlukus** [comment]
It works you just have to incline your tailwind custom classes like 
https://github.com/jeremiahlukus/demoAuth-revise-Jets/blob/styles/app/javascript/packs/theme.scss#L7

Instead of importing it from a file. You can import other non-tailwind css files. 

This is kind of an edge case most of the time you wont extend tailwind classes they dont recommend doing it either.
```
This guide only exists as a reference for people who need to integrate Tailwind with a preprocessor for reasons outside of their control, not because it is a recommended practice.
```

 So for the edge case you have to inline not really that bad.

**Comment by jeremiahlukus** [comment]
@tongueroo let me know if you want me to make any changes, ive used my branch at least 50 times testing a gem im working on starting from a fresh project.

**Comment by jeremiahlukus** [comment]
Screenshot 2023-09-21 at 10 08 33 AM

**Comment by jeremiahlukus** [comment]
"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.". Unable to merge. I have another PR to fix rubocop and adjust the workflows.

**Comment by jeremiahlukus** [comment]
Just a reminder I don’t have write access to merge this or the other PR

**Comment by jeremiahlukus** [comment]
@tongueroo  ping

**Comment by tongueroo** [comment]
Granted

**Pull request merged**
